export const Users = [
    {
        id: 1,
        profilePicture: "persons/person1.jpeg",
        username: "Safak Kocaoglu",
    },
    {
        id: 2,
        profilePicture: "persons/person2.jpeg",
        username: "Janet Doe",
    },
    {
        id: 3,
        profilePicture: "persons/person3.jpeg",
        username: "Alice Smith",
    },
    {
        id: 4,
        profilePicture: "persons/person4.jpeg",
        username: "Bob Johnson",
    },
    {
        id: 5,
        profilePicture: "persons/person5.jpeg",
        username: "Charlie Brown",
    },
    {
        id: 6,
        profilePicture: "persons/person6.jpeg",
        username: "David Wilson",
    },
    {
        id: 7,
        profilePicture: "persons/person7.jpeg",
        username: "Eve Davis",
    },
    {
        id: 8,
        profilePicture: "persons/person8.jpeg",
        username: "Frank Miller",
    },
    {
        id: 9,
        profilePicture: "persons/person9.jpeg",
        username: "Grace Lee",
    },
    {
        id: 10,
        profilePicture: "persons/person10.jpeg",
        username: "Henry Taylor",
    },
];

export const Posts = [
    {
        id :1,
        desc : "Hey! It's my first post.",
        photo : "posts/post1.jpg",
        date : "5 mins ago",
        userId : 1,
        like : 32,
        comment : 9,
    },
    {
        id :2,
        desc : "This is a sample post.",
        photo : "posts/post2.jpg",
        date : "10 mins ago",
        userId : 2,
        like : 15,
        comment : 5,
    },
    {
        id :3,
        desc : "Another day, another post.",
        photo : "posts/post3.jpg",
        date : "20 mins ago",
        userId : 3,
        like : 22,
        comment : 8,
    },
    {
        id :4,
        desc : "Loving the new features!",
        photo : "posts/post4.jpg",
        date : "30 mins ago",
        userId : 4,
        like : 18,
        comment : 6,
    },
    {
        id :5,
        desc : "Check out my latest update.",
        photo : "posts/post4.jpg",
        date : "1 hour ago",
        userId : 5,
        like : 25,
        comment : 10,
    },
    {
        id :6,
        desc : "Feeling great today!",
        photo : "posts/post4.jpg",
        date : "2 hours ago",
        userId : 6,
        like : 30,
        comment : 12,
    },
    {
        id :7,
        desc : "Just another post.",
        photo : "posts/post4.jpg",
        date : "3 hours ago",
        userId : 7,
        like : 28,
        comment : 7,
    },
    {
        id :8,
        desc : "Having a wonderful day!",
        photo : "posts/post4.jpg",
        date : "4 hours ago",
        userId : 8,
        like : 35,
        comment : 15,
    },
    {
        id :9,
        desc : "Excited for the weekend!",
        photo : "posts/post4.jpg",
        date : "5 hours ago",
        userId : 9,
        like : 40,
        comment : 20,
    },
    {
        id :10,
        desc : "Just chilling.",
        photo : "posts/post4.jpg",
        date : "6 hours ago",
        userId : 10,
        like : 50,
        comment : 25,
    },
]